# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

addons:
        apt:
                sources:
                        - llvm-toolchain-trusty-3.8
                packages:
                        - clang-3.8
                        - libclang-common-3.8-dev
                        - llvm-3.8-runtime

language: python
python:
        - 2.7

env:
        - COMPILER=clang-3.8
script: python tests/run.py
